Repository Delight-Momentum/Vote, pull requests merged in 2024-06, with the labels that each got.

#76 [#64] feat: 투표 페이지 공유하기 추가
  app/vote/[id]/result/page.tsx
  components/dialog-revote.tsx
  components/vote-form.tsx
  utils/share-kakao.ts
Labels: 기능구현 🚀, 리팩토링 🔨

#73 [#61] feat: 비밀번호 validation 추가
  components/create-vote-form.tsx
  components/dialog-delete.tsx
  components/vote-contents.tsx
  components/vote-form.tsx
  components/vote-participant-name.tsx
  components/vote-small-input.tsx
  components/vote-title.tsx
  cypress/e2e/create-vote.cy.ts
  cypress/e2e/edit-vote.cy.ts
Labels: 기능구현 🚀

#75 [#74] fix: 시작 날짜와 종료 날짜가 같고 00시 00분 일 때 투표 생성 막기
  components/create-vote-form.tsx
  hooks/use-date-picker.ts
Labels: 버그 🌈

#80 [#57] feat: GA 추가
  app/layout.tsx
  components/google-analytics.tsx
  components/index.ts
  gtag.d.ts
  package-lock.json
  package.json
  utils/gtag.ts
Labels: 기능구현 🚀

#78 [#77] refactor: 카드 클릭시 라우팅
  app/vote/[id]/result/page.tsx
  components/vote-card.tsx
  cypress/e2e/vote-main.cy.ts
Labels: 리팩토링 🔨

#88 [#79] refactor: 헤더 컴포넌트 반응형 추가
  components/header.tsx
Labels: 리팩토링 🔨

#92 [#81] feat: 투표 생성시 항목 삭제 버튼 추가
  components/create-vote-contents.tsx
  components/create-vote-form.tsx
  components/edit-vote-form.tsx
  components/index.ts
  components/input.tsx
  components/label.tsx
  components/radio-button.tsx
  components/vote-contents.tsx
  components/vote-period.tsx
  components/vote-select-content.tsx
  components/vote-select-radio.tsx
  components/vote-small-input.tsx
Labels: 기능구현 🚀

#93 [#85] feat: 카드 컴포넌트에 컨텐트 글자넘칠경우 ...처리
  components/vote-card.tsx
  components/vote-form.tsx
  components/vote-select-content.tsx
Labels: 기능구현 🚀

#94 [#86] feat: 카드 컴포넌트에 콘텐트 3개 이상 일 경우 숫자로 표시
  components/vote-card.tsx
Labels: 기능구현 🚀

#96 [#83] refactor: 공유하기 기능 데스크탑에선 모달 팝업, 모바일에선 web share api 적용
  app/vote/[id]/result/page.tsx
  components/button-share.tsx
  components/dialog-revote.tsx
  components/dialog-share.tsx
  components/index.ts
  components/vote-form.tsx
  cypress/e2e/vote-result.cy.ts
  public/icon-link.png
  public/kakao-logo.png
Labels: 리팩토링 🔨

#97 [#84] feat: 카드 컴포넌트 애니메이션 추가 및 디자인 수정
  components/vote-card.tsx
  components/vote-select-description.tsx
Labels: 기능구현 🚀, 리팩토링 🔨

#99 [#95] feat: 투표 리스트 필터 기능
  apis/get-votelist.ts
  app/page.tsx
  assets/svgs/filter-menu.tsx
  components/filter.tsx
  components/index.ts
  components/vote-card-list.tsx
Labels: 기능구현 🚀

#103 [#101] feat: VoteCard 컴포넌트 제목, 내용에 툴팁 추가
  components/index.ts
  components/tooltip.tsx
  components/vote-card.tsx
Labels: 기능구현 🚀

#102 [#100] fix: 투표페이지 항목 글자 넘치는 문제
  app/vote/[id]/result/page.tsx
  components/dialog.tsx
  components/label.tsx
  components/progress-bar.tsx
  components/vote-select-content.tsx
Labels: 버그 🌈

#104 [#98] feat: metadata 동적 생성
  apis/get-vote.ts
  app/vote/[id]/result/page.tsx
  components/progress-bar.tsx
  components/result-page-content.tsx
  cypress/e2e/vote-main.cy.ts
  stories/dialog.stories.tsx
Labels: 기능구현 🚀

#110 [#106] refactor: 메인페이지 검색, 필터 변경시 깜빡임 수정
  app/page.tsx
  components/vote-card-list.tsx
Labels: 리팩토링 🔨

#112 [#107] refactor: 카드 디자인 수정
  components/vote-card-list.tsx
  components/vote-card.tsx
  stories/vote-card.stories.tsx
Labels: 리팩토링 🔨

#113 [#109] feat: 검색 searchParams 적용
  app/globals.css
  app/page.tsx
  assets/svgs/search-cancel.svg
  components/header.tsx
  components/index.ts
  components/main-page-content.tsx
  styles/globals.css
Labels: 기능구현 🚀
